data:
  split_path: '/scratch/fcormier//t2k/ml/output_skdetsim//jun12_electronsCombine_1/train_val_test_gt200Hits_fcM50_2000MeVCut_nFolds30_fold0.npz' 
  dataset:
    h5file: '$SLURM_TMPDIR/multi_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDatasetDeadPMT
    pmt_positions_file: /scratch/fcormier/t2k/ml/image_files/skdetsim_imagefile.npy
    use_positions: False
    use_times: True
    geometry_file: /home/fcormier/t2k/ml/training/t2k_ml_training/data/geofile_skdetsim.npz
    channel_scaling:
      time: [400, 1000]
model:
  _target_: watchmal.model.resnet.resnet50
  num_input_channels: 2
  num_output_channels: 3
  stride: 1
  kernelSize: 1
  dropout_p: 0.1
  conv_pad_mode: 'circular'
engine:
  _target_: watchmal.engine.regression.RegressionEngine
  truth_key: 'positions'
tasks:
  train:
    epochs: 50
    val_interval: 200
    num_val_batches: 50
    checkpointing: false
    loss:
      _target_: watchmal.utils.custom_loss.OutsidePenaltyHuberLoss
      delta: 0.1
      penalty_weight_3rd: 5.
      penalty_weight_radius: 5.
      #_target_: torch.nn.HuberLoss
      #delta: 0.1
    data_loaders:
      train:
        split_key: train_idxs
        batch_size: 150
        num_workers: 10
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
      validation:
        split_key: val_idxs
        batch_size: 400
        num_workers: 6
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.01
      weight_decay: 0
    scheduler:
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.8
  evaluate:
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 1000
        num_workers: 2
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
gpu_list: 
- 0
- 1
- 2
- 3
seed: null
dump_path: ./outputs/
